name: CI

on: workflow_dispatch

jobs:
  build-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      pages: 'write'
      deployments: 'write'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      CI: ""
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.0.0
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
