name: CI

on: workflow_dispatch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      CI: ""
      INPUT_PATH: build
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.0.0
      with:
        path: build
